VARIABLES = dict(
    speed=dict(
        index=1,
        unit='m/s',
        min=0,
        max=100,
        type=1
    ),
    direction=dict(
        index=2,
        unit='deg',
        min=0,
        max=360,
        type=2
    ),
    height=dict(
        index=3,
        unit='m',
        min=0,
        max=1000,
        type=1
    ),
    temp=dict(
        index=4,
        unit='C',
        min=-50,
        max=50,
        type=1
    ),
    rain=dict(
        index=5,
        unit='mm/hr',
        min=0,
        max=100,
        type=1),
    rh=dict(
        index=6,
        unit='%',
        min=0,
        max=99,
        type=1
    ),
    pressure=dict(
        index=7,
        unit='Pa',
        min=20000,
        max=110000,
        type=1
    ),
)
